Description: >
    Deploys custom CMS which is used for variables encryption
Resources:
  #Encryption Key Creation (See Key Management Service KMS)
  KeyForEnvVarEncryption:
    Type: AWS::KMS::Key
    Properties:
      Description: "Key for sensitive data encryption"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS: "arn:aws:iam::<Account Number>:role/<Role>"
            Action:
              - "kms:Create*"
              - "kms:Encrypt"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
          - Sid: "Allow use of the key"
            Effect: "Allow"
            Principal:
              AWS: '*'
            Action:
              - "kms:Decrypt"
            Resource: "*"
  AliasForKeyForEnvVarEncryption:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/EncryptionKeyForEnvVariables
      TargetKeyId: !Ref KeyForEnvVarEncryption
  AnyConfigValue:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: String
      Name: '/serviceA/anyConfigValue'
      Type: String
      Value: 'ANY_CONFIG_VALUE'
  AnyOtherConfigValue:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: String
      Name: '/serviceA/anyOtherConfigValue'
      Type: String
      Value: 'ANY_OTHER_CONFIG_VALUE'
  ConfigValueByName:
      Type: "AWS::SSM::Parameter"
      Properties:
        Description: String
        Name: '/paramByName'
        Type: String
        Value: 'ANY_CONFIG_VALUE_REFERENCED_BY_NAME'

Outputs:
    EncryptionKeyForEnvVariables:
      Description: "Id of the key being used for en/decryption of the env variable"
      Value: !Ref KeyForEnvVarEncryption

    AliasForEncryptionKeyForEnvVariables:
      Description: "Alias of the key being used for en/decryption of the env variable"
      Value: !Ref AliasForKeyForEnvVarEncryption